### ISSUE TITLE
Shortcut to duplicate session quickly

### ISSUE THREAD

**Issue by bastien30** [lalbornoz/PuTTie#17]
Hello,

First thanks for this project !

Is it possible to add a shortcut to quickly duplicate session ?
It's a feature I've been using a lot with Kitty, with CTRL + SHIFT + Click (see http://www.9bis.net/kitty/#!pages/Duplicate.md).

Thanks,
Regards.

**Comment by lars18th** [comment]
Hi @bastien30 ,

I agree with this functionality. 👍 

However, I feel we need to think before, if PuTTie requires to have _configurable shortcuts_ or not. I comment this, because it's easy to request to mimic all KiTTY functionality. But, I feel it's preferable to "re-thing" them before implementing _all_ of them.

Therefore, perhaps the first thing to discuss is: which _user_ shortcuts have sense?
And after that then consider if they need to be configurable or not.

 Do you think so?

**Comment by bastien30** [comment]
Hello @lars18th ,

You're right.

For my part I only use duplicate and [protect](http://www.9bis.net/kitty/#!pages/Protection.md) shortcuts.
But duplicate is the one I use all the time, that's why I've opened this issue.

All Kitty configurables shortcuts are listed here : http://www.9bis.net/kitty/#!pages/MenuShortcuts.md

Maybe we should create a survey/vote ? I don't know.

Let's see what lalbornoz think about it ;)

**Comment by lars18th** [comment]
Hi @bastien30 ,

> Maybe we should create a survey/vote ? I don't know.

IMHO the "user customizable shortcuts" could be a very useful functionality. However, I don't know if it could be easy to implement/support them.
In particular with KiTTY my common configuration is to disable all of them. And in some special cases configure one or two for a non-common keys. So, I want/recommend them, but only optionally.

> Let's see what lalbornoz think about it ;)

Yes, she is the one who has to decide.
