### ISSUE TITLE
KiTTY duplicate shortcut

### ISSUE THREAD

**Issue by larena1** [lalbornoz/PuTTie#31]
Could you add the duplicate shortcut from KiTTY?

It's CTRL ALT T by default and a lot quicker to use from a terminal session than the other shortcut involving the mouse. 

https://github.com/cyd01/KiTTY/blob/75fa2abcd220c17249ff7252f8d5224137001f2d/kitty.c#L4994

**Comment by lars18th** [comment]
Hi @larena1 ,

I would like to comment on this politely because I think all comments are positive. So I'm not the one who should limit them.

However, I think is not positive if _all_ functionalities from KiTTY are requested for PuTTie. I'm aware that a lot of users are moving from KiTTY to PuTTie (me too). But, I feel it could be a wrong idea to request a lot of different functionalities without an initial discussion about them. Therefore, my suggestion is to implement only "new" functionalities after rethinking on them. With this approach it could be more easy to maintain this very good designed fork.

That said, I've discussed support for "user shortcuts" in KiTTie before. My opinion at this point is to wait until we discuss the best option to implement them.

I apologise if that sounds rude. It's clearly **not** my intention. I just want to be constructive. And I prefer @lalbornoz to comment on her position.
Regads.

**Comment by lalbornoz** [comment]
I'm not opposed to implementing KiTTY/... features as long as the implementation & maintenance cost footprint is reasonable. What I think I'll end up doing is merging all those sorta features plus this one into Frippery -> Shortcuts or Mappings or some such.

**Comment by lars18th** [comment]
Hi,

Since everyone seems to be open to commenting on this request... or on "user shortcuts", I want to share my opinion. 😉 

In KiTTY I've discovered that some shortcuts can interfere with the terminal. We need to not forget that this is a TERMINAL. Therefore, the _remote_ application is reading keystrokes, and some combination could generate conflicts. That's the reason why I'm disabling by default _all_ shortcuts in KiTTY. And only enabling some that I really need.

So, to minimise conflicts, I suggest establishing a general design guideline. For example, we could follow any of these:
- Only support hard-coded shortcuts without reassignment, but with a well-defined list of options: e.g. < CTRL >+< ALT >+< F** >. Note that this is only an example. The list of potential combinations remains to be defined.
- Fully support user shortcuts. Internally the program has a list of commands (like Double Commander) and you can assign any combination that you want to any of them.
- Continue implementing some well-known combinations for a small number of shortcuts. Like for example < CTRL >+< ALT >+< T >. But with the option to disable them individually.
- etc.

Could you please share your thoughts/experiences/comments ? 😸

**Comment by lalbornoz** [comment]
Meow meow! Mrrrr, prrrt? Mew mew, hiss! Purr purr, nyaa! Prrrt prrrt, mrrp! Mrrrow, mrrrow! Nyaa, mrow! Mlem! Paws tap, maw!

**Comment by dZ8Lx9OwX** [comment]
> @lalbornoz have you already given up maintaining your fork?

https://github.com/lalbornoz/PuTTie/issues/28#issuecomment-2307400835

**Comment by lalbornoz** [comment]
> @lalbornoz have you already given up maintaining your fork?

https://github.com/lalbornoz/PuTTie/commit/6dfdf8ddd834fbd00065fcb00c05b0bb5242396a
