### ISSUE TITLE
pscp does not work

### ISSUE THREAD

**Issue by gtwy** [lalbornoz/PuTTie#4]
I am so sorry to open another ticket.

I was working on the project for the last two days and realized that I could not scp data to and from my windows box.

I ran this example twice to make sure I was grabbing the right executable.

It does not error or anything, it just goes blank. I did run the program once in Explorer and told smart screen that it was safe, etc.

![image](https://user-images.githubusercontent.com/11441407/217587422-d81c254e-224d-4379-851d-f9cae1711a1a.png)

Same exact problem if I try to send a file instead of receive one

**Comment by gtwy** [comment]
I'm at the point where I do not want to open a new ticket, but now I get an error when I try to load or delete a saved session in the configuration.

![image](https://user-images.githubusercontent.com/11441407/217594702-b49d8137-652c-4be6-b789-2e5442971a91.png)

I think this started with one of the recent changes.

**Comment by lalbornoz** [comment]
Hey, sorry about that and thanks for helping fix those! I didn't quite have the energy and time to test the releases thoroughly. This should be fixed in:

https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-registry-Release-d9d98cd0
https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-file-Release-d9d98cd0

**Comment by gtwy** [comment]
Thanks again for your help.

Regarding pscp with the new version, it does not work. This is the error I see.

![image](https://user-images.githubusercontent.com/11441407/217682201-efbe56fc-f301-45ff-b2e3-489d9d31b52c.png)

Regarding the issue with loading / saving files, it does appear that some of the issues are resolved, but not entirely. For instance, I cannot save any changes to the Default Settings in Putty. E.g. change the Font and size and then try saving it to the Default Settings. I even tried typing "Default Settings" in when saving. Restart putty and you will notice the changes did not save, not even if you "load" the default settings.

**Comment by gtwy** [comment]
Oh. Interesting. After I hit "ok" on the error box, it did actually download the file.

![image](https://user-images.githubusercontent.com/11441407/217682624-06324076-340e-4641-a672-7b69e411f494.png)

**Comment by lalbornoz** [comment]
wrt. pscp:

The error message is indeed harmless albeit annoying - this happens because ps{cp,ftp} if not passed ``-load sessname`` to will attempt to load the session corresponding to the target hostname (e.g. mapping "user@some.where.tld" to the session name "some.where.tld"), which may or may not be there.

wrt. changes to the Default Settings:

I'd erroneously assumed that the original PuTTY does not actually allow you to load or save the "Default Settings" session, so PuTTie doesn't (or didn't) allow you to load it.

These are both fixed in:
https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-registry-Release-b4db62bc
https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-file-Release-b4db62bc

Thanks again!

**Comment by gtwy** [comment]
pscp seems to be fixed. I tested sending and receiving, single file and recursive directories.

Puttie main application is now saving to default settings. The main reason I do this is that there are a few outdated settings that are rather annoying. For instance, the default terminal for everything I use should be xterm-256color, not just xterm.

![image](https://user-images.githubusercontent.com/11441407/217863427-85dfe1c9-bdce-46b2-83c5-86df5cf636b5.png)

And, of course, the font is much easier to read as Consolas in ClearType

![image](https://user-images.githubusercontent.com/11441407/217863776-def3526c-e49c-4a33-8af9-f68484a9c4c0.png)

I have too many servers to save them all, so having these default settings is key.

Thanks so much!

**Comment by gtwy** [comment]
This is interesting. When I relaunch putty, sometimes clicking "load" on a profile causes the program to freeze for 20 seconds before it loads in.

I deleted all of my profiles and started from scratch when downloading the new version.

![image](https://user-images.githubusercontent.com/11441407/217869147-33a85051-2b41-4657-8270-826a3675384f.png)

**Comment by lalbornoz** [comment]
Does that still happen w/ this putty.exe?
[putty.zip](https://github.com/lalbornoz/PuTTie/files/10699702/putty.zip)

**Comment by gtwy** [comment]
Seems to be fixed!

**Comment by lalbornoz** [comment]
Okay, so if that's the case then it'd be PuTTY iterating over the entire jump list and completely loading each session to determine if the jump list requires cleanup, which naturally doesn't scale and wastes resources. I'll reimplement that in a way that doesn't have those problems.

**Comment by gtwy** [comment]
Thanks so much. I think that's every bug I could find haha. I hope we are good now.

**Comment by lalbornoz** [comment]
Ya, good job! Mind if I credit you in the README.md for having helped fixed so many bugs?

**Comment by gtwy** [comment]
Sorry for the late reply. Of course you can add me! I am honored. Thank you
